@host = http://127.0.0.1:8080/v1


### Login
POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}


### Token verification
GET {{host}}/verify-token?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEwMCwiZXhwIjoxNjU0MTYyNjk1fQ.Ry-n-qB4y0iooHIfjKtW0ujk2U0Mj5n0NjY1PUND2i4 HTTP/1.1

