@host = http://127.0.0.1:8080/v1/cats


@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEwMCwiZXhwIjoxNjUzNjM1MDUyfQ.WlfaJkcH3GxAVCDKfnI6x5utgxnqJp0pNuC6ITvwaj0

### Get all cats via id
GET {{host}}/?fields=id&offset=0&limit=2&token={{token}} HTTP/1.1

### Get single cat name
GET {{host}}/6?fields=name&token={{token}} HTTP/1.1

### Get all cats with id and name
GET {{host}}/?token={{token}} HTTP/1.1

###
POST {{host}}/?token={{token}} HTTP/1.1
Content-Type: application/json

{
    "id": 0,
    "name": "Lili"
}


###
PUT {{host}}/ HTTP/1.1
Content-Type: application/json

{
    "id": 2,
    "name": "Fifi"
}


###
DELETE {{host}}/1 HTTP/1.1


